### ISSUE TITLE
根据 ETH Beijing Hackathon 项目提交说明 所做的Demo Todo list

### ISSUE THREAD

**Issue by yanboishere** [Web3-Club/Web3-Interactive-Learning#40]
ETH Beijing Hackathon 的项目需要提交到

https://github.com/WTFAcademy/ETHBeijing/blob/main/team-info.md

PR（Pull-Request）截止时间为 2023年4月8日 下午15:00。你需要在你的项目下更新以下内容:

- [x] - 项目名称
- [x] #45
- [x] - 简介
- [x] - 队长和队员
- [x] - 目标
- [x] - 黑客松前两日的进度
- [x] #44
- [x] - 项目 github repo 链接
- [x] - 是否基于之前的项目，如果有，给出详细信息。
- [x] - 项目 Demo 链接（选填）
